server:
  port: 80
mybatis:
  mapper-locations: classpath:mybatis/**
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssm?characterEncoding=UTF-8&serverTimezone=GMT/%2B8
    username: root
    password: root
